# Generated by Django 2.2.2 on 2019-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('refno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sendername', models.CharField(max_length=50)),
                ('senderaddress', models.TextField()),
                ('sendermobo', models.CharField(max_length=50)),
                ('receivername', models.CharField(max_length=50)),
                ('receiveraddress', models.TextField()),
                ('receivermobo', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('charge', models.IntegerField()),
                ('postdate', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
