# Generated by Django 2.2.2 on 2019-06-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='name',
            new_name='username',
        ),
    ]
